"""First Migration

Revision ID: 5950359bfc57
Revises: 29828a7e7d89
Create Date: 2022-05-13 17:42:16.007162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5950359bfc57'
down_revision = '29828a7e7d89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
